const affirmations = [
    "I am capable of achieving anything I set my mind to.",
    "I radiate love and positivity to those around me.",
    "I am grateful for all the blessings in my life.",
    "I am in charge of my own happiness.",
    "I choose to see the good in every situation.",
    "I am confident and believe in myself.",
    "I attract positive and supportive people into my life.",
    "I am worthy of love, success, and happiness.",
    "I am resilient and can overcome any challenge.",
    "I embrace change and adapt easily to new situations.",
    "I deserve to live a life filled with joy and abundance.",
    "I am enough just as I am.",
    "I release all negative thoughts and embrace positivity.",
    "I trust my intuition and make decisions with confidence.",
    "I am constantly growing and evolving into a better version of myself.",
    "I forgive myself and others, and release any grudges.",
    "I am open to receiving all the good things life has to offer.",
    "I am a magnet for success and abundance.",
    "I let go of fear and embrace courage in every aspect of my life.",
    "I am surrounded by love and support.",
    "I am proud of myself and all that I have accomplished.",
    "I am worthy of respect and treat others with kindness.",
    "I am in control of my thoughts and choose positive ones.",
    "I attract positive opportunities and experiences.",
    "I am healthy, strong, and full of vitality.",
    "I am grateful for the lessons I learn from both successes and failures.",
    "I am at peace with myself and the world around me.",
    "I trust the journey of my life and know that everything happens for a reason.",
    "I am focused and driven towards achieving my goals.",
    "I am surrounded by abundance, and my needs are always met.",
    "I am worthy of love and allow it to flow into my life effortlessly.",
    "I release all self-doubt and have faith in my abilities.",
    "I am a unique individual with valuable contributions to offer the world.",
    "I am open to new opportunities and embrace them with excitement.",
    "I am free to create the life of my dreams.",
    "I attract positive and fulfilling relationships into my life.",
    "I am worthy of success and achieve it with ease.",
    "I release all resistance and trust the flow of life.",
    "I am in control of my emotions and choose to be happy.",
    "I am grateful for the abundance that surrounds me.",
    "I believe in myself and my ability to overcome any obstacle.",
    "I am proud of myself and all that I have accomplished.",
    "I am deserving of all the good things that come my way.",
    "I am constantly growing and evolving into a better version of myself.",
    "I attract positive and loving people into my life.",
    "I am open to receiving love and giving love freely.",
    "I release all negative self-talk and embrace self-compassion.",
    "I am confident in my abilities and trust my decisions.",
    "I am in alignment with my true purpose and follow my passion.",
    "I am capable of achieving greatness.",
    "I am deserving of happiness, love, and success.",
    "I attract positive opportunities that lead to my personal and professional growth.",
    "I am grateful for the abundance in my life and the abundance yet to come.",
    "I am open to receiving and giving love in all its forms.",
    "I trust myself and my intuition to guide me in the right direction.",
    "I am a powerful creator, and I manifest my desires with ease.",
    "I release all limiting beliefs and embrace my unlimited potential.",
    "I am surrounded by positive and supportive people who believe in me.",
    "I am a magnet for success and attract it effortlessly.",
    "I embrace challenges as opportunities for growth and learning.",
    "I am worthy of all the good things that come my way.",
    "I am grateful for the present moment and find joy in it.",
    "I release all past resentments and forgive myself and others.",
    "I am open to receiving abundance in all areas of my life.",
    "I trust in the process of life and know that everything unfolds perfectly.",
    "I am focused, determined, and driven towards achieving my goals.",
    "I deserve to live a life filled with happiness, love, and fulfillment.",
    "I am confident in my abilities to overcome any obstacles.",
    "I attract positive and like-minded people who support me.",
    "I release all fears and step into my power.",
    "I am worthy of all the success and abundance that comes my way.",
    "I am grateful for the love and support I receive from others.",
    "I believe in my dreams and work towards them with dedication.",
    "I am deserving of love, happiness, and all the good things in life.",
    "I embrace change and see it as an opportunity for growth.",
    "I am grateful for my body and treat it with love and respect.",
    "I am open to receiving guidance from my higher self.",
    "I am capable of creating the life I desire.",
    "I attract abundance and prosperity into my life.",
    "I let go of the past and live in the present moment.",
    "I am filled with gratitude for all the blessings in my life.",
    "I trust myself and make decisions with confidence and clarity.",
    "I am worthy of all the love and happiness in the world.",
    "I release all negative energy and welcome positivity into my life.",
    "I am resilient and can overcome any challenges that come my way.",
    "I am open to receiving miracles in my life.",
    "I am deserving of success, abundance, and fulfillment.",
    "I am surrounded by love, joy, and positive energy.",
    "I believe in myself and my ability to achieve my goals.",
    "I am worthy of all the good things life has to offer.",
    "I trust the universe to guide me towards my highest good.",
    "I am confident in my skills and talents.",
    "I am open to receiving abundance in all areas of my life.",
    "I release all negative thoughts and embrace positivity.",
    "I am deserving of love, respect, and kindness.",
    "I am in control of my own happiness.",
    "I attract positive and uplifting experiences into my life.",
    "I am grateful for all the opportunities that come my way.",
    "I trust my intuition to guide me towards the right path.",
    "I am a unique individual with valuable gifts to offer the world.",
    "I am worthy of success and achieve it with grace and ease.",
    "I am open to receiving love and give it freely.",
    "I am capable of handling anything that comes my way.",
    "I am deserving of all the good things in life.",
    "I release all worries and trust that everything will work out for the best.",
    "I am a magnet for positive experiences and loving relationships.",
    "I am grateful for the abundance that flows into my life.",
    "I am open to receiving guidance and support from the universe.",
    "I am worthy of love, happiness, and success.",
    "I believe in myself and my ability to achieve my goals.",
    "I release all self-limiting beliefs and embrace my true potential.",
    "I am deserving of all the good things that come my way.",
    "I am confident and believe in my abilities.",
    "I attract positive and supportive people into my life.",
    "I am open to receiving all the love and abundance the universe has to offer.",
    "I am resilient and can overcome any challenges that come my way.",
    "I am in control of my thoughts and choose to focus on the positive.",
    "I am worthy of success and achieve it with determination and persistence.",
    "I am grateful for all the lessons life has taught me.",
    "I am surrounded by love and support from those around me.",
    "I am proud of myself and all that I have accomplished.",
    "I am deserving of respect and treat others with kindness.",
    "I trust myself and make decisions with confidence.",
    "I attract positive opportunities and experiences into my life.",
    "I am healthy, vibrant, and full of energy.",
    "I am grateful for the growth and transformation I experience every day.",
    "I am at peace with myself and the world around me.",
    "I trust the journey of my life and embrace it with an open heart.",
    "I am focused and committed to achieving my goals.",
    "I am surrounded by abundance, and my needs are always met.",
    "I am worthy of love and receive it with open arms.",
    "I release all self-doubt and step into my power.",
    "I am a unique individual with valuable contributions to make.",
    "I am open to new opportunities and embrace them fearlessly.",
    "I am free to create the life of my dreams.",
    "I attract positive and fulfilling relationships into my life.",
    "I am deserving of success and achieve it with determination.",
    "I release all resistance and go with the flow of life.",
    "I am in control of my emotions and choose happiness.",
    "I am grateful for the abundance that surrounds me.",
    "I believe in myself and my ability to overcome any challenge.",
    "I am proud of myself and all that I have accomplished.",
    "I am deserving of all the good things that come my way.",
    "I am constantly growing and evolving into a better version of myself.",
    "I attract positive and loving people into my life.",
    "I am open to receiving love and giving it unconditionally.",
    "I release all negative self-talk and embrace self-love.",
    "I am confident in my abilities and trust my decisions.",
    "I am aligned with my true purpose and live it every day.",
    "I am capable of achieving greatness in all areas of my life."
];

const colors = [
    "rgb(233, 172, 125)",
    "rgb(125, 191, 233)",
    "rgb(157, 146, 244)",
    "rgb(233, 125, 143)",
    "rgb(192, 233, 125)",
    "rgb(125, 166, 233)"
];
const randomColor = colors[Math.floor(Math.random() * colors.length)];


const affirmation = document.getElementById('affirmation');
affirmation.style.color = randomColor;

const storedAffirmation = localStorage.getItem('todaysAffirmation');
const storedDate = localStorage.getItem('lastAffirmationDate');
const today = new Date().toLocaleDateString();

if (storedAffirmation && storedDate === today) {
    affirmation.innerText = storedAffirmation;
}
else {
    const newAffirmation = affirmations[Math.floor(Math.random() * affirmations.length)];
    affirmation.innerText = newAffirmation;

    localStorage.setItem('todaysAffirmation', newAffirmation);
    localStorage.setItem('lastAffirmationDate', today);
}
